In [1]:
#Consider the below code to answer further questions:
import numpy as np
list_ = [1,2,3,4,5]
array_list = np.array(object = list_)

In [2]:
#Is there any difference in the data type of variables list_ and array_list? If there is then write a codeto print the
#data types of both the variables.
import numpy as np
list_ = [1,2,3,4,5]
print(list_)
print()
array_list = np.array(object = list_)
print(array_list)
print()
print(type(list_))
print()
type(array_list)

# list_ data in list form while array_list make n dimensional array

[1, 2, 3, 4, 5]

[1 2 3 4 5]

<class 'list'>



numpy.ndarray

In [3]:
#Write a code to print the data type of each and every element of both the variables list_ and arra_list.
import numpy as np
list_ = [1,2,3,4,5]
print(list_)
print()
array_list = np.array(object = list_)

print(type(list_))

print(array_list.dtype)


[1, 2, 3, 4, 5]

<class 'list'>
int64


In [4]:
''' Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.'''
import numpy as np
list_ = [1,2,3,4,5]
print(list_)
print()
array_list = np.array(object = list_)
array_list = np.array(object = list_, dtype = int)
array_list.dtype

type(list_)

[1, 2, 3, 4, 5]



list

In [5]:
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

# Write a code to find the following characteristics of variable, num_array:
#(i) shape
#(ii) size

print(num_array.shape)
print(num_array.size)

(2, 3)
6


In [6]:
#Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
#creation function.
#[Hint: The size of the array will be 9 and the shape will be (3,3).]

import numpy.matlib as nm
nm.zeros((3,3))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# Create an identity matrix of shape (5,5) using numpy functions?
#[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
import numpy.matlib as nm
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])